### ISSUE TITLE
collisions on nao's feet

### ISSUE THREAD

**Issue by mikaelarguedas** [ros-naoqi/nao_moveit_config#8]
@nlyubova:  could you PR the disable collisions that were missing in the srdf since 166c9f3b4d7de0e1ac31d94b5af4d466ae574396 and that you fixed on your repo in nlyubova@12b29db38a8b267424cd0473b2868cec7bdeb878 ?
Does that fix the collision on the robot feet ?
Thanks!

**Comment by nlyubova** [comment]
done! sorry completely forgot to do a PR last time...

but still the foots are red.... maybe you know why?

**Comment by vrabaud** [comment]
Merged #9, any ideas on the feet ?

**Comment by mikaelarguedas** [comment]
I can try to rerun the moveit setup assistant it should fix it I just
thought that this was already fixed in nlyubova package. Will look into it
shortly

**Comment by nlyubova** [comment]
@keulYSMB unfortunately the fix of dependencies mentioned earlier does not fix collision on feet...  I can re-run moveit_setup assistant and see if can fix it ;)

**Comment by mikaelarguedas** [comment]
fixed in ebd2048999cad8f66611d32544cfeb3100ffc1a4
